### ISSUE TITLE
TypeError: urlopen() got multiple values for keyword argument 'body'

### ISSUE THREAD

**Issue by McOrts** [artikcloud/tutorial-python-sdksample#1]
When a execute in a Raspberry Pi a code similar to tutorial-python-sdksample/**app-send-message.py**. I obtain the error:
`Traceback (most recent call last):
  File "c_last_events.py", line 58, in <module>
    main(sys.argv[1:])
  File "c_last_events.py", line 51, in main
    api_response = api_instance.send_message(data)
  File "/usr/local/lib/python2.7/dist-packages/artikcloud/apis/messages_api.py", line 1019, in send_message
    (data) = self.send_message_with_http_info(data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/artikcloud/apis/messages_api.py", line 1097, in send_message_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/dist-packages/artikcloud/api_client.py", line 323, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/artikcloud/api_client.py", line 150, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/artikcloud/api_client.py", line 368, in request
    body=body)
  File "/usr/local/lib/python2.7/dist-packages/artikcloud/rest.py", line 248, in POST
    body=body)
  File "/usr/local/lib/python2.7/dist-packages/artikcloud/rest.py", line 148, in request
    headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 135, in request_encode_body
    **urlopen_kw)
**TypeError: urlopen() got multiple values for keyword argument 'body**'
`
My version of the urllib3 is:
`pi@raspberrypi:~ $ aptitude show python-urllib3
Package: python-urllib3                  
State: installed
Automatically installed: yes
Version: 1.9.1-3
`
What can I do?

**Comment by yujingwu** [comment]
Internal DX-1402
Jonathan, please take a look.

**Comment by jonathanpaek** [comment]
@McOrts can you share results with a newer version of urllib3.  Version 1.9.1-3 may be outdated.
https://pypi.python.org/pypi/urllib3

**Comment by McOrts** [comment]
I need to uninstall the library because was imposible tu upgrade. 
@jonathanpaek Reinstalled successfully with `$ python setup.py install` and the problem was fixed.
Thanks.

**Comment by jonathanpaek** [comment]
Thank you for confirming @McOrts

**Comment by sachin-apporbit** [comment]
I faced this issue for following setup:
OS: ubuntu
browser: Chrome/Firefox
framework: Selenium+robot

Solution: Just upgrade urllib3 to the latest version. Command as follows:
sudo pip install --upgrade --ignore-installed urllib3

Done!
